/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Klasa zapytania o uzyskanie tokena dostępowego zgodnego z OAuth2
type TokenRequest struct {

	// Określa czy dana sesja jest związana z interakcją z PSU – wartości true/false. Rozszerzenie standardu OAuth2.
	IsUserSession bool `json:"is_user_session,omitempty"`

	// IP przeglądarki użytkownika (informacja na potrzeby fraud detection). Rozszerzenie standardu OAuth2. Wymagany dla is_user_session = true.
	UserIp string `json:"user_ip,omitempty"`

	RequestHeader *RequestHeaderWithoutTokenAs `json:"requestHeader,omitempty"`

	ScopeDetails *ScopeDetailsInput `json:"scope_details,omitempty"`

	// Adres usługi TPP, na które zostanie wykonane przekierowanie po wygenerowaniu tokena dostępowego przez ASPSP. Wymagany dla grant_type=authorization_code.
	RedirectUri string `json:"redirect_uri,omitempty"`

	// Identyfikator TPP. Wymagany dla grant_type=authorization_code.
	ClientId string `json:"client_id,omitempty"`

	// Typy zgód o które prosi TPP. Lista identyfikatorów zgodna ze specyfikacją standardu Polish API.
	Scope string `json:"scope,omitempty"`

	// Wartość tokena, który służy do uzyskania nowego tokena dostępowego dla tego samego zakresu zgód (scope, scope_details) - w przypadku gdy pierwotny token utraci swoją ważność, lub dla zawężonego zakresu zgód. Wymagany dla grant_type=refresh_token.
	RefreshToken string `json:"refresh_token,omitempty"`

	// Typ zastosowanej autoryzacji. Jedna z wartości: authorization_code, refresh_token (rozszerzenie standardu OAuth2)
	GrantType string `json:"grant_type"`

	// Kod autoryzacji uzyskany podczas żądania do usługi /authorize OAuth2. Wymagany dla grant_type=authorization_code.
	Code string `json:"Code,omitempty"`

	// Informacja dotycząca wersji przeglądarki użytkownika (informacja na potrzeby fraud detection). Rozszerzenie standardu OAuth2. Wymagany dla is_user_session = true.
	UserAgent string `json:"user_agent,omitempty"`
}
