/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GrantType string

// List of GrantType
const (
	AUTHORIZATION_CODE GrantType = "authorization_code"
	IMPLICIT GrantType = "implicit"
	PASSWORD GrantType = "password"
	REFRESH_TOKEN GrantType = "refresh_token"
	CLIENT_CREDENTIALS GrantType = "client_credentials"
	URNIETFPARAMSOAUTHGRANT_TYPESAML2_BEARER GrantType = "urn:ietf:params:oauth:grant-type:saml2-bearer"
	URNPINGIDENTITYCOMOAUTH2GRANT_TYPEVALIDATE_BEARER GrantType = "urn:pingidentity.com:oauth2:grant_type:validate_bearer"
)
