/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Kolekcja kluczy (certyfikatów - dla kryptografii asymetrycznej), które mogą zostać użyte przez ASPSP dla podpisu odpowiedzi API. Zgodnie RFC 7591 i RFC 7517. Wymagane warunkowo o ile nie podano jwks_uri. / A collection of keys (certificates - for asymmetric cryptography) that can be used by ASPSP for API response signature. RFC 7591 and RFC 7517 compliant. Required conditionally unless jwks_uri is specified.
type Jwks struct {

	Keys []Jwk `json:"keys"`
}
