/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Klasa zapytania o pojedynczą transakcję / Transaction Detail Request Class
type TransactionDetailRequest struct {

	// Numer konta nadawcy / Sender account number
	AccountNumber string `json:"accountNumber"`

	RequestHeader *RequestHeaderAis `json:"requestHeader"`

	// ID elementu (transakcji lub blokadzie) nadany przez ASPSP / Element (transaction or hold) ID (ASPSP)
	ItemId string `json:"itemId"`

	// Data zaksięgowania operacji, YYYY-MM-DDThh:mm:ss[.mmm] / Transaction booking date
	BookingDate time.Time `json:"bookingDate,omitempty"`
}
