/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Algorithm string

// List of Algorithm
const (
	HS256 Algorithm = "HS256"
	HS384 Algorithm = "HS384"
	HS512 Algorithm = "HS512"
	SHA256WITH_RSA Algorithm = "SHA256withRSA"
	SHA384WITH_RSA Algorithm = "SHA384withRSA"
	SHA512WITH_RSA Algorithm = "SHA512withRSA"
	ES256 Algorithm = "ES256"
	ES256_K Algorithm = "ES256K"
	ES384 Algorithm = "ES384"
	ES512 Algorithm = "ES512"
	PS256 Algorithm = "PS256"
	PS384 Algorithm = "PS384"
	PS512 Algorithm = "PS512"
	ED_DSA Algorithm = "EdDSA"
	NONE Algorithm = "none"
)
