/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Odpowiedź dotycząca poprawnej rejestracji aplikacji klienckiej / The response of the correct registration of the client application
type RegistrationResponse struct {

	Scope string `json:"scope,omitempty"`

	LogoUri string `json:"logo_uri,omitempty"`

	ClientName string `json:"client_name,omitempty"`

	ClientId string `json:"client_id,omitempty"`

	TokenEndpointAuthMethod *TokenEndpointAuthMethod `json:"token_endpoint_auth_method,omitempty"`

	ClientSecretExpiresAt time.Time `json:"client_secret_expires_at,omitempty"`

	Contacts []string `json:"contacts,omitempty"`

	ClientIdIssuedAt time.Time `json:"client_id_issued_at,omitempty"`

	ClientUri string `json:"client_uri,omitempty"`

	PolicyUri string `json:"policy_uri,omitempty"`

	RedirectUris []string `json:"redirect_uris,omitempty"`

	SoftwareId string `json:"software_id,omitempty"`

	SoftwareVersion string `json:"software_version,omitempty"`

	TosUri string `json:"tos_uri,omitempty"`

	Jwks *Jwks `json:"jwks,omitempty"`

	ResponseTypes []ResponseType `json:"response_types,omitempty"`

	GrantTypes []GrantType `json:"grant_types,omitempty"`

	JwksUri string `json:"jwks_uri,omitempty"`

	ClientSecret string `json:"client_secret,omitempty"`
}
