/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Klasa opisująca parametry częśtotliwości wykonywania płatności cyklicznej / A class defining parameters of the frequency of recurring paymenets
type RecurringTransferFrequency struct {

	// Typ jednostki okresu czasu / The type of unit of time period
	PeriodType string `json:"periodType"`

	// Wartość jednostki okresu czasu / The value of unit of time period
	PeriodValue int32 `json:"periodValue"`
}
