/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Klasa zawierająca informacje o PSU na potrzeby usług autoryzacji / PSU Information Class dedicated for authorization services
type RequestHeaderWithoutTokenAs struct {

	// Oryginalna data wysłania, format: YYYY-MM-DDThh:mm:ss[.mmm] / Send date
	SendDate time.Time `json:"sendDate,omitempty"`

	// Adres IP końcowego urządzenia PSU. Wymagany dla isDirectPsu=true. / IP address of PSU's terminal device. Required when isDirectPsu=true.
	IpAddress string `json:"ipAddress,omitempty"`

	// Browser agent dla PSU / PSU browser agent
	UserAgent string `json:"userAgent,omitempty"`

	// Identyfikator TPP / TPP ID
	TppId string `json:"tppId"`

	// Identyfikator żądania w formacie UUID (Wariant 1, Wersja 1) zgodnym ze standardem RFC 4122 / Request ID using UUID format (Variant 1, Version 1) described in RFC 4122 standard
	RequestId string `json:"requestId"`

	// Wartość identyfikatora kontekstu w jakim występuje PSU. Wymagany warunkowo - w przypadku wysyłania żądania dla takiego PSU, który może występować w więcej niż jednym kontekście w wybranym ASPSP. / The value of context that is used by PSU. Required conditionally - in case context of the request is used and PSU may use more then one context for the ASPSP.
	PsuContextIdentifierValue string `json:"psuContextIdentifierValue,omitempty"`

	// Typ identyfikatora PSU, służy do wskazania przez TPP na podstawie jakiej informacji zostanie zidentyfikowany PSU, który będzie podlegał uwierzytelnieniu. Wartość słownikowa. / PSU identifier type, used by TPP to indicate type of information based on which the PSU is to be authenticated. Dictionary value.
	PsuIdentifierType string `json:"psuIdentifierType,omitempty"`

	// Typ identyfikatora kontekstu w jakim występuje PSU. Wartość słownikowa. Wymagany warunkowo - w przypadku wysyłania żądania dla takiego PSU, który może występować w więcej niż jednym kontekście w wybranym ASPSP. / Identifier of context that is used by PSU. Dictionary value. Required conditionally - in case context of the request is used and PSU may use more then one context for the ASPSP.
	PsuContextIdentifierType string `json:"psuContextIdentifierType,omitempty"`

	// Wartość identyfikatora PSU. Wymagany warunkowo - w przypadku gdy została przekazana niepusta wartość typu identyfikatora PSU. / The value of the PSU's identifier. Required conditionally - in case non empty value of PSU identifier type was passed.
	PsuIdentifierValue string `json:"psuIdentifierValue,omitempty"`

	// (true / false) Znacznik oznaczający czy żądanie jest wysyłane w kontekście PSU korporacyjnego
	IsCompanyContext bool `json:"isCompanyContext,omitempty"`
}
