/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Klasa odpowiedzi na pytanie o status paczki płatności / Response data with status of bundle of payments
type BundleResponse struct {

	BundleId *BundleId `json:"bundleId"`

	// Status paczki przelewów / Bundle of payments status
	BundleStatus string `json:"bundleStatus,omitempty"`

	// Identyfikator paczki przelewów nadany przez TPP. / Bundle of payments identifier set by TPP.
	TppBundleId string `json:"tppBundleId"`

	// Szczegółowy status paczki przelewów / Bundle of payments detailed status
	BundleDetailedStatus string `json:"bundleDetailedStatus,omitempty"`

	ResponseHeader *ResponseHeader `json:"responseHeader"`

	Payments []PaymentInfo `json:"payments,omitempty"`
}
