/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Klasa odpowiedzi na zapytanie o transakcję /  Transaction Detail Response Class
type TransactionDetailResponse struct {

	// Data ważności blokady, YYYY-MM-DDThh:mm:ss[.mmm] / Hold expiration date
	HoldExpirationDate time.Time `json:"holdExpirationDate,omitempty"`

	// Przyczyna odrzucenia / Reason for rejection
	RejectionReason string `json:"rejectionReason,omitempty"`

	// Data kursu waluty, YYYY-MM-DDThh:mm:ss[.mmm] / Date of the currency exchange rate
	CurrencyDate time.Time `json:"currencyDate,omitempty"`

	// Kwota w oryginalnej walucie / Amount of the transaction
	AmountBaseCurrency string `json:"amountBaseCurrency,omitempty"`

	CardInfo *TransactionInfoCard `json:"cardInfo,omitempty"`

	ResponseHeader *ResponseHeader `json:"responseHeader"`

	BaseInfo *TransactionInfo `json:"baseInfo"`

	// Unikalny identyfikator transakcji po stronie TPP / Transaction ID (TPP)
	TppTransactionId string `json:"tppTransactionId,omitempty"`

	// Unikalny identyfikator instrumentu płatniczego, za którego pomocą wykonano transakcję / Payment Instrument ID
	UsedPaymentInstrumentId string `json:"usedPaymentInstrumentId,omitempty"`

	// Waluta oryginalna transakcji, kod ISO / Currency of the transaction, ISO code
	BaseCurrency string `json:"baseCurrency,omitempty"`

	UsInfo *TransactionInfoTax `json:"usInfo,omitempty"`

	ZusInfo *TransactionInfoZus `json:"zusInfo,omitempty"`

	TransactionRate []CurrencyRate `json:"transactionRate,omitempty"`

	// Nazwa TPP / TPP name
	TppName string `json:"tppName,omitempty"`
}
