/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Lista atrybutów uprawnienia do żądania statusu paczki płatności / The list of attributes of the bundle of payments status request privilege
type PrivilegeBundle struct {

	// Rodzaj limitu zgody / Type of limit of usages
	ScopeUsageLimit string `json:"scopeUsageLimit,omitempty"`

	// Identyfikator paczki przelewów nadany przez TPP. Jeżeli to pole jest puste należy uzupełnić pole bundleId. / Bundle of payments identifier set by TPP. If this field is empty then bundleId must be filled.
	TppBundleId string `json:"tppBundleId,omitempty"`

	// Identyfikator paczki płatności. Jeżeli to pole jest puste należy uzupełnić pole tppBundleId. / Bundle of payments ID. If this field is empty then tppBundleId must be filled.
	BundleId string `json:"bundleId,omitempty"`
}
