/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Klasa zapytania o uzyskanie kodu autoryzacyjnego zgodnego z OAuth2
type AuthorizeRequest struct {

	// Losowa, unikalna w ramach TPP wartość – zabezpieczenie przed atakiem Cross-Site Request Forgery
	State string `json:"state"`

	// Typy zgód o które prosi TPP. Lista identyfikatorów zgodna ze specyfikacją standardu Polish API.
	Scope string `json:"scope"`

	ScopeDetails *ScopeDetailsInput `json:"scope_details"`

	// Adres usługi TPP, na które zostanie wykonane przekierowanie po uwierzytelnieniu klienta ASPSP
	RedirectUri string `json:"redirect_uri"`

	// Identyfikator TPP
	ClientId string `json:"client_id"`

	// Typ odpowiedzi. Wartość stała: code
	ResponseType string `json:"response_type"`

	RequestHeader *RequestHeaderWithoutTokenAs `json:"requestHeader"`
}
