/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Klasa zapytania o rachunki / Accounts Request Class
type AccountsRequest struct {

	// Używane w celu stronicowania danych: wielkość strony danych / Page size (paging info)
	PerPage int32 `json:"perPage,omitempty"`

	RequestHeader *RequestHeaderAisCallback `json:"requestHeader"`

	// Używane w celu stronicowania danych: identyfikator strony, która ma zostać zwrócona w odpowiedzi / Used for paging the results. Identifier of the page to be returned in the response.
	PageId string `json:"pageId,omitempty"`
}
