/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Klasa odpowiedzi na zapytanie TPP o wygenerowanie tokena dostępowego
type TokenResponse struct {

	// Typy zgód które uzyskał TPP. Lista identyfikatorów zgodna ze specyfikacją standardu Polish API.
	Scope string `json:"scope,omitempty"`

	ScopeDetails *ScopeDetailsOutput `json:"scope_details"`

	ResponseHeader *ResponseHeader `json:"responseHeader"`

	// Wartość wygenerowanego tokena dostępowego
	AccessToken string `json:"access_token"`

	// Wartość wygenerowanego tokena służącego do uzyskania nowego tokena dostępowego bez konieczności ponownej autoryzacji
	RefreshToken string `json:"refresh_token,omitempty"`

	// Czas ważności tokena dostępowego, po którym zostanie on unieważniony. Wartość wyrażona w sekundach, od momentu wygenerowania odpowiedzi.
	ExpiresIn string `json:"expires_in"`

	// Typ tokena dostępowego. Dozwolona wartość to Bearer.
	TokenType string `json:"token_type"`
}
