/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Klasa zawierająca dane banku używana w żądaniach AIS / AIS Bank Data Class
type Bank struct {

	// Nazwa Banku / Bank's name
	Name string `json:"name,omitempty"`

	// Numer BIC/SWIFT Banku / BIC/SWIFT number
	BicOrSwift string `json:"bicOrSwift,omitempty"`

	// Kod Banku, dla przelewów zagranicznych / Bank's code
	Code string `json:"code,omitempty"`

	Address *Address `json:"address,omitempty"`

	// Kod kraju 3166-1 / Country code
	CountryCode string `json:"countryCode,omitempty"`
}
