/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Lista atrybutów uprawnienia do inicjacji przelewu zagranicznego EEA / The list of attributes of the EEA foreign transfer request initiation privilege
type PrivilegeForeignTransferEea struct {

	Sender *SenderPisForeign `json:"sender,omitempty"`

	// Droga jaką przelew ma być rozliczony / The way the transfer should be settled
	System string `json:"system"`

	// Tryb pilności / Urgency mode
	DeliveryMode string `json:"deliveryMode,omitempty"`

	Recipient *RecipientPisForeign `json:"recipient,omitempty"`

	// Rodzaj limitu zgody / Type of limit of usages
	ScopeUsageLimit string `json:"scopeUsageLimit,omitempty"`

	TransferData *TransferDataCurrencyRequired `json:"transferData,omitempty"`

	// Tryb realizacji płatności. Nadrzędna informacja decydująca o tym w jakim trybie zostanie zrealizowana płatność. / Payment execution mode. The superior information deciding which mode is to be used to execute payment.
	ExecutionMode string `json:"executionMode,omitempty"`
}
