/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Klasa zlecenia zdefiniowania nowej płatności cyklicznej / Recurring payment definition Request Class
type RecurringPaymentRequest struct {

	TaxPayment *RecurringTaxPayment `json:"taxPayment,omitempty"`

	DomesticPayment *RecurringDomesticPayment `json:"domesticPayment,omitempty"`

	EEAPayment *RecurringEeaPayment `json:"EEAPayment,omitempty"`

	RequestHeader *RequestHeaderCallback `json:"requestHeader"`

	// Typ przelewu, który zostanie wykorzystany do zdefiniowania nowej płatności cyklicznej  / The type of payment that is to be used to define new recurring payment
	TypeOfPayment string `json:"typeOfPayment"`

	// Identyfikator płatności cyklicznej nadany przez TPP / Recurring payment identifier set by TPP
	TppRecurringPaymentId string `json:"tppRecurringPaymentId"`

	NonEEAPayment *RecurringNonEeaPayment `json:"nonEEAPayment,omitempty"`

	Recurrence *RecurringTransferParameters `json:"recurrence"`
}
