/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Klasa informacji o koncie / Account Information Class
type AccountInfo struct {

	AccountType *DictionaryItem `json:"accountType"`

	// Saldo księgowe rachunku - po wykonaniu transakcji / Book balance of the account
	BookingBalance string `json:"bookingBalance"`

	Bank *BankAccountInfo `json:"bank,omitempty"`

	// Rodzaj posiadacza rachunku: osoba fizyczna lub osoba prawna / Account holder type: individual person or corporation
	AccountHolderType string `json:"accountHolderType"`

	// Nazwa typu rachunku (definiowana przez ASPSP) / Account's type name (defined by ASPSP)
	AccountTypeName string `json:"accountTypeName,omitempty"`

	// Numer rachunku / Account number
	AccountNumber string `json:"accountNumber"`

	// Waluta rachunku / Currency
	Currency string `json:"currency"`

	NameAddress *NameAddress `json:"nameAddress,omitempty"`

	AuxData *ModelMap `json:"auxData,omitempty"`

	// Dostępne środki - po wykonaniu transakcji / Available funds
	AvailableBalance string `json:"availableBalance"`

	// Nazwa konta ustawiona przez klienta / Account name set by the client
	AccountNameClient string `json:"accountNameClient,omitempty"`
}
