/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Lista atrybutów uprawnienia do zdefiniowania nowej płatności cyklicznej / The list of attributes of definition of new recurring payment request privilege
type PrivilegeRecurringPayment struct {

	TaxPayment *RecurringTaxPayment `json:"taxPayment,omitempty"`

	DomesticPayment *RecurringDomesticPayment `json:"domesticPayment,omitempty"`

	EEAPayment *RecurringEeaPayment `json:"EEAPayment,omitempty"`

	// Typ przelewu, który zostanie wykorzystany do zdefiniowania nowej płatności cyklicznej  / The type of payment that is to be used to define new recurring payment
	TypeOfPayment string `json:"typeOfPayment"`

	// Rodzaj limitu zgody / Type of limit of usages
	ScopeUsageLimit string `json:"scopeUsageLimit,omitempty"`

	NonEEAPayment *RecurringNonEeaPayment `json:"nonEEAPayment,omitempty"`

	Recurrence *RecurringTransferParameters `json:"recurrence,omitempty"`
}
