/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Klasa informacji o płatniku do ZUS / Polish Social Security Institution (ZUS) Payor Information Class
type SocialSecurityPayor struct {

	// Numer Identyfikacji Podatkowej / Payor's Tax Identification Number
	Nip string `json:"nip,omitempty"`

	// Typ dodatkowego identyfikatora płatnika / Payor's additional identifier type
	AdditionalPayorIdType string `json:"additionalPayorIdType,omitempty"`

	// Dodatkowy numer identyfikacyjny płatnika / Payor's additional identification number
	AdditionalPayorId string `json:"additionalPayorId,omitempty"`
}
