/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Klasa informacji o płatności / Payment Information Class
type PaymentInfo struct {

	// Szczegółowy status płatności / Detailed payment status
	DetailedStatus string `json:"detailedStatus"`

	// Tryb realizacji płatności. Nadrzędna informacja decydująca o tym w jakim trybie zostanie zrealizowana płatność. / Payment execution mode. The superior information deciding which mode is to be used to execute payment.
	ExecutionMode string `json:"executionMode"`

	GeneralStatus *PaymentStatus `json:"generalStatus"`

	PaymentId *PaymentId `json:"paymentId"`

	// ID transakcji nadany przez TPP / Transaction ID (TPP)
	TppTransactionId string `json:"tppTransactionId"`
}
