/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type KeyOperation string

// List of KeyOperation
const (
	SIGN KeyOperation = "sign"
	VERIFY KeyOperation = "verify"
	ENCRYPT KeyOperation = "encrypt"
	DECRYPT KeyOperation = "decrypt"
	WRAP_KEY KeyOperation = "wrapKey"
	UNWRAP_KEY KeyOperation = "unwrapKey"
	DERIVE_KEY KeyOperation = "deriveKey"
	DERIVE_BITS KeyOperation = "deriveBits"
)
