/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Klasa odpowiedzi na żądanie inicjacji paczki przelewów. Zawiera dane o statusach poszczególnych przelewów oraz status paczki. / Class describing statuses of each payment inside the bundle and the bundle itself.
type PaymentsBundleResponse struct {

	BundleId *BundleId `json:"bundleId,omitempty"`

	// Status paczki przelewów / Bundle of payments status
	BundleStatus string `json:"bundleStatus,omitempty"`

	Payments []PaymentInfo `json:"payments,omitempty"`

	// Szczegółowy status paczki przelewów / Bundle of payments detailed status
	BundleDetailedStatus string `json:"bundleDetailedStatus,omitempty"`

	ResponseHeader *ResponseHeader `json:"responseHeader"`
}
