/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Klasa zapytania o dostępne środki płatnicze na rachunku / Confirmation of Funds Request Class
type ConfirmationOfFundsRequest struct {

	// Numer konta / Account number
	AccountNumber string `json:"accountNumber"`

	// Kod ISO Waluty (waluta transakcji) / Currency of transaction (ISO)
	Currency string `json:"currency"`

	RequestHeader *RequestHeaderWithoutToken `json:"requestHeader"`

	// Wielkość środków której dotyczy zaptanie / Amount of the transaction
	Amount string `json:"amount"`
}
