/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Klucz JWK (JSON Web Key). Zgodnie z RFC 7591 i RFC 7517. / A key (JSON Web Key). RFC 7591 and RFC 7517 compliant.
type Jwk struct {

	X5t string `json:"x5t,omitempty"`

	Use *Use `json:"use,omitempty"`

	Dp string `json:"dp,omitempty"`

	P2s string `json:"p2s,omitempty"`

	X5u string `json:"x5u,omitempty"`

	D string `json:"d,omitempty"`

	X5c []string `json:"x5c,omitempty"`

	Qi string `json:"qi,omitempty"`

	X string `json:"x,omitempty"`

	Crv string `json:"crv,omitempty"`

	Alg *Algorithm `json:"alg,omitempty"`

	P2c string `json:"p2c,omitempty"`

	Q string `json:"q,omitempty"`

	KeyOps []KeyOperation `json:"key_ops,omitempty"`

	E string `json:"e,omitempty"`

	Cty string `json:"cty,omitempty"`

	X5tS256 string `json:"x5t#S256,omitempty"`

	Kty *KeyType `json:"kty"`

	N string `json:"n,omitempty"`

	Dq string `json:"dq,omitempty"`

	Kid string `json:"kid,omitempty"`

	K string `json:"k,omitempty"`

	Y string `json:"y,omitempty"`

	P string `json:"p,omitempty"`
}
