/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Klasa zapytania o elementy (transakcje lub blokady) / Element (transaction or hold) Information Request Class
type HoldRequest struct {

	// Używane w celu stronicowania danych: wielkość strony danych / Page size (paging info)
	PerPage int32 `json:"perPage,omitempty"`

	// Element filtru: data księgowania od, YYYY-MM-DD. Ignorowane w przypadku pobierania listy blokad. / Filter element. Ignored during list of holds retrieval.
	BookingDateFrom string `json:"bookingDateFrom,omitempty"`

	// Element filtru: data transakcji od, YYYY-MM-DD / Filter element
	TransactionDateFrom string `json:"transactionDateFrom,omitempty"`

	// Element filtru: kwota do / Filter element
	MaxAmount string `json:"maxAmount,omitempty"`

	// Element filtru: data transakcji do, YYYY-MM-DD / Filter element
	TransactionDateTo string `json:"transactionDateTo,omitempty"`

	// Element filtru: elementy od podanego identyfikatora (transakcji lub blokady) / Filter element - id of transaction or hold to start from
	ItemIdFrom string `json:"itemIdFrom,omitempty"`

	RequestHeader *RequestHeaderAisCallback `json:"requestHeader"`

	// Numer rachunku / Account number
	AccountNumber string `json:"accountNumber"`

	// Element filtru: data księgowania do, YYYY-MM-DD. Ignorowane w przypadku pobierania listy blokad. / Filter element. Ignored during list of holds retrieval.
	BookingDateTo string `json:"bookingDateTo,omitempty"`

	// Używane w celu stronicowania danych: identyfikator strony, która ma zostać zwrócona w odpowiedzi / Used for paging the results. Identifier of the page to be returned in the response.
	PageId string `json:"pageId,omitempty"`

	// Element filtru: kwota od / Filter element
	MinAmount string `json:"minAmount,omitempty"`

	// Element filtru: transakcji / Filter element
	Type_ string `json:"type,omitempty"`
}
