/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"DeleteConsent",
		strings.ToUpper("Post"),
		"/v2_1_1.1/accounts/v2_1_1.1/deleteConsent",
		DeleteConsent,
	},

	Route{
		"GetAccount",
		strings.ToUpper("Post"),
		"/v2_1_1.1/accounts/v2_1_1.1/getAccount",
		GetAccount,
	},

	Route{
		"GetAccounts",
		strings.ToUpper("Post"),
		"/v2_1_1.1/accounts/v2_1_1.1/getAccounts",
		GetAccounts,
	},

	Route{
		"GetHolds",
		strings.ToUpper("Post"),
		"/v2_1_1.1/accounts/v2_1_1.1/getHolds",
		GetHolds,
	},

	Route{
		"GetTransactionDetail",
		strings.ToUpper("Post"),
		"/v2_1_1.1/accounts/v2_1_1.1/getTransactionDetail",
		GetTransactionDetail,
	},

	Route{
		"GetTransactionsCancelled",
		strings.ToUpper("Post"),
		"/v2_1_1.1/accounts/v2_1_1.1/getTransactionsCancelled",
		GetTransactionsCancelled,
	},

	Route{
		"GetTransactionsDone",
		strings.ToUpper("Post"),
		"/v2_1_1.1/accounts/v2_1_1.1/getTransactionsDone",
		GetTransactionsDone,
	},

	Route{
		"GetTransactionsPending",
		strings.ToUpper("Post"),
		"/v2_1_1.1/accounts/v2_1_1.1/getTransactionsPending",
		GetTransactionsPending,
	},

	Route{
		"GetTransactionsRejected",
		strings.ToUpper("Post"),
		"/v2_1_1.1/accounts/v2_1_1.1/getTransactionsRejected",
		GetTransactionsRejected,
	},

	Route{
		"GetTransactionsScheduled",
		strings.ToUpper("Post"),
		"/v2_1_1.1/accounts/v2_1_1.1/getTransactionsScheduled",
		GetTransactionsScheduled,
	},

	Route{
		"Authorize",
		strings.ToUpper("Post"),
		"/v2_1_1.1/auth/v2_1_1.1/authorize",
		Authorize,
	},

	Route{
		"Token",
		strings.ToUpper("Post"),
		"/v2_1_1.1/auth/v2_1_1.1/token",
		Token,
	},

	Route{
		"GetConfirmationOfFunds",
		strings.ToUpper("Post"),
		"/v2_1_1.1/confirmation/v2_1_1.1/getConfirmationOfFunds",
		GetConfirmationOfFunds,
	},

	Route{
		"Bundle",
		strings.ToUpper("Post"),
		"/v2_1_1.1/payments/v2_1_1.1/bundle",
		Bundle,
	},

	Route{
		"CancelPayments",
		strings.ToUpper("Post"),
		"/v2_1_1.1/payments/v2_1_1.1/cancelPayments",
		CancelPayments,
	},

	Route{
		"CancelRecurringPayment",
		strings.ToUpper("Post"),
		"/v2_1_1.1/payments/v2_1_1.1/cancelRecurringPayment",
		CancelRecurringPayment,
	},

	Route{
		"Domestic",
		strings.ToUpper("Post"),
		"/v2_1_1.1/payments/v2_1_1.1/domestic",
		Domestic,
	},

	Route{
		"EEA",
		strings.ToUpper("Post"),
		"/v2_1_1.1/payments/v2_1_1.1/EEA",
		EEA,
	},

	Route{
		"GetBundle",
		strings.ToUpper("Post"),
		"/v2_1_1.1/payments/v2_1_1.1/getBundle",
		GetBundle,
	},

	Route{
		"GetMultiplePayments",
		strings.ToUpper("Post"),
		"/v2_1_1.1/payments/v2_1_1.1/getMultiplePayments",
		GetMultiplePayments,
	},

	Route{
		"GetPayment",
		strings.ToUpper("Post"),
		"/v2_1_1.1/payments/v2_1_1.1/getPayment",
		GetPayment,
	},

	Route{
		"GetRecurringPayment",
		strings.ToUpper("Post"),
		"/v2_1_1.1/payments/v2_1_1.1/getRecurringPayment",
		GetRecurringPayment,
	},

	Route{
		"NonEEA",
		strings.ToUpper("Post"),
		"/v2_1_1.1/payments/v2_1_1.1/nonEEA",
		NonEEA,
	},

	Route{
		"Recurring",
		strings.ToUpper("Post"),
		"/v2_1_1.1/payments/v2_1_1.1/recurring",
		Recurring,
	},

	Route{
		"Tax",
		strings.ToUpper("Post"),
		"/v2_1_1.1/payments/v2_1_1.1/tax",
		Tax,
	},

	Route{
		"Register",
		strings.ToUpper("Post"),
		"/v2_1_1.1/register/v2_1_1.1/register",
		Register,
	},
}
